version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcde
      POSTGRES_DB: wallet
    ports:
      - 5456:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
